pybo/views/answer_views.py
from flask import Blueprint, render_template, redirect, url_for, request, g, flash
from datetime import datetime

from pybo import db
from pybo.views.auth_views import login_required     
# migrate는 안가지고오네
from ..forms import AnswerForm
from pybo.models import Question, Answer

bp = Blueprint("answer", __name__, url_prefix="/answer")

# 삭제
@bp.route("/delete/<int:answer_id>")
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash("삭제 권한이 없습니다")
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

# 수정
@bp.route("/modify/<int:answer_id>", methods=("GET", "POST"))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()     # 이걸로 검사함
        if form.validate_on_submit():
            form.populate_obj(answer)   # form에 answer를 채우는 게 맞는거 같애
                # form은 클래스 모델 객체잖아
            answer.modify_date = datetime.now() # 수정일시저장
            db.session.commit()
            return redirect("{}#answer_{}".format(url_for('question.detail', question_id=answer.question.id), answer.id))
    else:   # get 
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', form=form)
            
            

@bp.route("/create/<int:question_id>", methods=["POST"])
@login_required
def create(question_id):
    form = AnswerForm()    
    question = Question.query.get_or_404(question_id)
    
    if request.method == "POST" and form.validate_on_submit():
        content = request.form.get("content")
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
            # wow: g.user는 @bp.before_app_request 애너테이션에 의해 생성
            # g.user는 로그인한 사용자야
        '''
            answer = Answer(question=question, content, create_date=datetime.now())
            db.session.add(answer)
            db.session.commit()
            이렇게 해도, 저장가능 >> 존나 불편하네
            question=릴레이션할 질문 적는겨
        '''
        question.answer_set.append(answer)
        db.session.commit()
        return redirect("{}#answer_{}".format(url_for('question.detail', question_id=question_id), answer.id))

    return render_template('question/question_detail.html', question=question, form=form)

# 추천
@bp.route("/vote/<int:answer_id>")
@login_required
def vote(answer_id):
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        _answer.voter.append(g.user)
        db.session.commit()
    return redirect("{}#answer_{}".format(url_for('question.detail', question_id=_answer.question.id), _answer.id))

pybo/views/question_views.py
from flask import Blueprint, render_template, url_for, redirect, request, g, flash

from datetime import datetime

from pybo.views.auth_views import login_required

from .. import db
from ..models import Question, Answer, User
from ..forms import QuestionForm, AnswerForm

bp = Blueprint("question", __name__, url_prefix="/question")

@bp.route('/list/')
def _list():
    page = request.args.get("page", default=1, type=int)    # page
    kw = request.args.get('kw', default='', type=str)    
    
    question_list = Question.query.order_by(Question.create_date.desc())
    if kw:
        search = "%%{}%%".format(kw);
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        question_list = question_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(Question.subject.ilike(search) |    # 질문제목
                    Question.content.ilike(search) |    # 질문내용
                    User.username.ilike(search) |       # 질문작성자
                    sub_query.c.content.ilike(search) | # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    )\
            .distinct()

    question_list = question_list.paginate(page, per_page=10)
    return render_template("question/question_list.html", question_list=question_list, page=page, kw=kw)

@bp.route("/detail/<int:question_id>")
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template("question/question_detail.html", question=question, form=form)

@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = QuestionForm()
    
    if request.method == "POST" and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
        
    return render_template("question/question_form.html", form=form)

@bp.route('/modify/<int:question_id>', methods=("GET", "POST"))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == "POST":
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)     # populate_obj : form 변수의있는 데이터를 question 객체에 업데이트
            question.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:   # get request
        form = QuestionForm(obj=question)
        return render_template('question/question_form.html', form=form)        

# 질문삭제
@bp.route("/delete/<int:question_id>")
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제 권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    # 위에 if문이 작동안했다는건, g.user == question.user 의미지
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))
        
        
# 질문추천
@bp.route("/vote/<int:question_id>")
@login_required
def vote(question_id):
    _question = Question.query.get_or_404(question_id)
    if g.user == _question.user:
        flash('본인이 작성한 글은 추천할 수 없습니다')
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/templates/question/question_detail.html
<!-- 질문 상세보기 -->

{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <!-- flash 오류 출력 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject}}</h2>

    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content | markdown }}</div>
            <div class="d-flex justify-content-end">
                <!-- 질문수정시간 -->
                {% if question.modify_date %}
                <div class="badge bg-light text-start text-dark p-2 mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date|datetime }}</div>
                </div>
                {% endif%}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.user.username}}</div>
                    <div>{{ question.create_date | datetime}}</div>
                </div>
            </div>
            <!-- 질문 추천, 수정, 삭제 -->
            <div class="my-3">
                <!-- 추천 -->
                <a href="javascript:void(0)" data-uri="{{ url_for('question.vote', question_id=question.id) }}" class="recommend btn bnt-sm btn-outline-secondary">추천
                    <span class="badge rounded-pill bg-success">{{ question.voter|length}}</span>
                </a>
                {% if g.user == question.user %}
                <!-- 수정 -->
                <a href="{{ url_for('question.modify', question_id=question.id) }}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <!-- 삭제 -->
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
                {% endif %}
            </div>

        </div>
    </div>

    <!-- 답변목록 -->
    <h5 class="border-bottom my-3 p-2">{{ question.answer_set | length }}개의 답변이 있습니다</h5>
    {% for answer in question.answer_set %}
    <!-- 앵커태그는 유일해야하므로 -->
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content | markdown }}</div>
            <div class="d-flex justify-content-end">
                <!-- 답변 수정 시간 -->
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark text-start p-2 mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date| datetime }}</div>
                </div>
                {% endif %}

                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.user.username }}</div>
                    <div>{{ answer.create_date | datetime }}</div>
                </div>
            </div>
            <!-- 답변수정 버튼 -->
            <div class="my-3">
                <!-- 추천 -->
                <a href="javascript:void(0)" data-uri="{{ url_for('answer.vote', answer_id=answer.id) }}" class="recommend btn btn-sm btn-outline-secondary">추천<span class="badge rounded-pill bg-success">{{ answer.voter|length}}</span></a>
                {% if g.user == answer.user %}
                <!-- question.answer_set, for문에서 answer준다 -->
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변등록 -->
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <textarea {% if not g.user %} disabled {% endif %} name="content" id="content" rows="10"
                class="form-control"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

{% block script%}
<script>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            if (confirm('정말 삭제 하시겠습니까?')) {
                location.href = this.dataset.uri;
            }
        })
    })

    // 질문 추천 스크립트
    const recommend_elements = document.getElementsByClassName('recommend')
    Array.from(recommend_elements).forEach(function(element){
        element.addEventListener('click', function(){
            if(confirm('정말로 추천 하시겠습니까?')){
                location.href = this.dataset.uri;
            }
        })
    })
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}

{% block content %}
<!-- Register a question  -->


<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>

    <!-- ! action 지정 안하면, 자기 자신한테 전달  -->
    <!-- ! 자기 자신이 http://127.0.0.1:5000/question/create -->
    <!-- 자기 자신이 자기자신 route고  -->
    <!-- action 지정안하면, 다른 모듈에서도 사용가능 -->
    <form method="post" class="post-form my-3">
        {{ form.csrf_token() }}
        <!-- 오류표시 start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
                <strong>{{ form[field].label }}</strong>
                <ul>
                    {% for error in errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 end -->
        <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" name="subject" class="form-control" id="subject" value="{{ form.subject.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea name="content" id="content" rows="10" class="form-control">{{ form.content.data or '' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

pybo/templates/question/question_list.html
<!-- 질문 목록 -->

{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 검색창 -->
    <div class="row my-3">
        <div class="col-6">
            <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <!-- 검색창 end -->

    <table class="table small">
        <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
                {% for question in question_list.items %}
                    <tr class="text-center">
                        <td>{{ question_list.total - ((question_list.page -1) * question_list.per_page) - loop.index0 }} </td>
                        <td class="text-start">
                            <a href="{{ url_for('question.detail', question_id=question.id)}}">{{ question.subject}}</a>
                            {% if question.answer_set|length > 0 %}
                                <span class="text-danger small mx-2">{{ question.answer_set|length }}</span>
                            {% endif %}
                        </td>
                        <td>{{ question.user.username }}</td><!-- 글쓴이 추가 -->
                        <td>{{ question.create_date | datetime}}</td>
                    </tr>
                {% endfor %}

            {% else %}
                    <tr>
                        <td colspan="3">질문이 없습니다</td>
                    </tr>
            {% endif %}
        </tbody>
    </table>

    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- preview page -->
        {% if question_list.has_prev%}
            <li class="page-item">
                <a class="page-link" href="javascript:void(0)" data-page="{{ question_list.prev_num }}">[이전]</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a href="javascript:void(0)" class="page-link" tabindex="-1" aria-disabled="true">[이전]</a>
            </li>
        {% endif %}

        <!--page number -->
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)" >{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <a href="javascript:void(0)" class="page-link">{{ page_num }}</a>
                    </li>
                {% endif %}

            {% else %}
                    <li class="disabled">
                        <a href="javascript:void(0)" class="page-link">...</a>
                    </li>
            {% endif %}
        {% endfor %}

        <!-- next page -->
        {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{ question_list.next_num}}" href="javascript:void(0)">[다음]</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a href="javascript:void(0)" tabindex="-1" class="page-link" aria-disabled="true">[다음]</a>
            </li>
        {% endif %}
    </ul>
    <!-- paging end -->
</div>
<form action="{{ url_for('question._list') }}" id="searchForm" method="get">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}

{% block script %}
<script type="text/javascript">
    // 각각 누를때 사용해야 하는듯 >> form 에 적용하려고 했는데 안됐음
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function(){
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });

    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });

</script>
{% endblock %}